name: Integration Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: HW1 test
        id: selftest
        uses: EQSP-Task-Manager/hw1-draft@master
