name: Integration Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - name: Cache Flutter dependencies
        uses: actions/cache@v1
        with:
          path: /opt/hostedtoolcache/flutter
          key: ${{ runner.OS }}-flutter-install-cache-${{ env.flutter_version }}

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test --coverage

      - name: HW1 test
        id: selftest
        uses: EQSP-Task-Manager/hw1@master

  build_check:
    needs: [build]
    if: success() || failure()
    runs-on: ubuntu-latest  
    steps:
      - uses: EQSP-Task-Manager/hw3@main
        with:
          bot_token: 5796796413:AAHsr0zr4E_Bk2ACiF0I_GCUWmr8GkArVIc
          bot_chat_id: -675020997
          is_sucess: ${{ job.status == 'success' }}
          project_name: Done App